import os
import sys
import json

# Ensure the root directory is in the Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from agent_repository.core.tool_interface import ToolInterface
from agent_repository.core.llm_service import LLMService

class ReasoningEngine(ToolInterface):
    """
    A strategic tool that acts as an interface to the powerful local LLM (Mixtral).
    It translates a high-level idea into a structured, machine-readable business plan.
    """
    def __init__(self):
        print(f"[{self.name}] Initializing and connecting to the LLM Service...")
        # This engine holds the instance of the core brain
        # The LLMService will be instantiated only when this tool is first initialized.
        self.llm_service = LLMService()

    @property
    def name(self) -> str:
        return "strategic_planner_and_writer"

    @property
    def description(self) -> str:
        return "Takes a high-level idea and uses a powerful LLM to generate a comprehensive business and creative plan in a structured JSON format."

    def execute(self, **kwargs) -> dict:
        """
        Generates the full business plan by calling the LLM Service.

        Args:
            idea (str): The high-level creative concept.

        Returns:
            dict: A dictionary representing the structured business plan.
        """
        idea = kwargs.get("idea", "a default idea")
        print(f"[{self.name}] Generating business plan via LLM for: '{idea}'")

        # Get the raw JSON string from the LLM
        raw_json_plan = self.llm_service.generate_plan(idea)

        # Parse and validate the JSON
        try:
            plan_dict = json.loads(raw_json_plan)
            print(f"[{self.name}] Successfully parsed the business plan generated by the LLM.")
            return plan_dict
        except json.JSONDecodeError as e:
            print(f"[{self.name}] CRITICAL ERROR: Failed to parse JSON from LLM output. Error: {e}")
            print(f"Raw output was:\n---\n{raw_json_plan}\n---")
            return {"error": "Failed to parse the plan from the LLM.", "raw_output": raw_json_plan}